// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-2n7ro-5BzNIDknBLd4OSkLaEYko8fGo',
    appId: '1:129232862772:web:2e15dd1f0d332697621461',
    messagingSenderId: '129232862772',
    projectId: 'chat-bot-bba68',
    authDomain: 'chat-bot-bba68.firebaseapp.com',
    storageBucket: 'chat-bot-bba68.firebasestorage.app',
    measurementId: 'G-J7WLGSJCNM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBp_A4vSIb_d1RIbLXaje_XFD29UxSTVaM',
    appId: '1:129232862772:android:f1e3385ff5970dd5621461',
    messagingSenderId: '129232862772',
    projectId: 'chat-bot-bba68',
    storageBucket: 'chat-bot-bba68.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrcV24aRJtPisWPuWi1c_dcypgqJUSFOI',
    appId: '1:129232862772:ios:5c7341333e7a6be2621461',
    messagingSenderId: '129232862772',
    projectId: 'chat-bot-bba68',
    storageBucket: 'chat-bot-bba68.firebasestorage.app',
    iosClientId: '129232862772-ujn3icovgtrhj8n4rcuqakoq1ng0d3rv.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatBot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrcV24aRJtPisWPuWi1c_dcypgqJUSFOI',
    appId: '1:129232862772:ios:5c7341333e7a6be2621461',
    messagingSenderId: '129232862772',
    projectId: 'chat-bot-bba68',
    storageBucket: 'chat-bot-bba68.firebasestorage.app',
    iosClientId: '129232862772-ujn3icovgtrhj8n4rcuqakoq1ng0d3rv.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatBot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-2n7ro-5BzNIDknBLd4OSkLaEYko8fGo',
    appId: '1:129232862772:web:dd767e18194dba81621461',
    messagingSenderId: '129232862772',
    projectId: 'chat-bot-bba68',
    authDomain: 'chat-bot-bba68.firebaseapp.com',
    storageBucket: 'chat-bot-bba68.firebasestorage.app',
    measurementId: 'G-Q2KN6W5E01',
  );
}
